# Configuration you want to make available to your components
Facilities:
  HTTPServer: true
  JSONWs: true
  #RuntimeCtl: true
  #ServiceErrorManager: true
HTTPServer:
  Address: 0.0.0.0
  Port: 8080
  AccessLogging: true
  AccessLog:
    LogLinePreset: "framework"
ApplicationLogger:
  GlobalLogLevel: INFO
